const adjectives = [
    "glum",
    "fluffy",
    "hairy",
    "goofy",
    "stinky",
    "wonky",
    "loopy",
    "lumpy",
    "floppy",
    "slippery",
    "crooked",
    "no-show",
    "over-the-counter",
    "babbling",
    "hydraulic",
    "lizard-like",
    "droopy",
    "deadbeat",
    "wannabe",
    "second hand",
    "rubbery",
    "homemade",
    "bubbly",
    "mismatched",
    "sparse",
    "dense",
    "smooth",
    "squeaky",
    "smelly",
    "sour",
    "sour-tasting"
]

export default adjectives;