const verbs = [
    "juggle",
    "snort",
    "prance",
    "scramble",
    "skedaddle",
    "nuzzle",
    "flip",
    "squish",
    "tickle",
    "schmooze",
    "poke",
    "discard",
    "disrupt",
    "invade",
    "disassemble",
    "evaporate",
    "unwrap",
    "postpone",
    "detach",
    "intercept",
    "disconnect",
    "demolish",
    "twaddle",
    "scatter",
    "shrink",
    "deconstruct"
]

export default verbs;